version: '3.6'

services:
  voter-distro:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    image: nodejs
    container_name: voter-distro
    restart: unless-stopped
    volumes:
      - tmp:/tmp
      - ./src:/app:rw
volumes:
    tmp:
